name: 'Check PR Trigger'
description: 'Determine if a PR should be created, closed, or skipped based on commit message'
outputs:
  action:
    description: 'Action to take: create, close, or skip'
    value: ${{ steps.check.outputs.action }}
runs:
  using: 'composite'
  steps:
    - name: Check Commit Message
      id: check
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%s)
        echo "DEBUG: Checking commit message: '$COMMIT_MSG'"
        if echo "$COMMIT_MSG" | grep -qE "^create-pr\(.+\)$"; then
          echo "Action: create PR"
          echo "action=create" >> $GITHUB_OUTPUT
        elif echo "$COMMIT_MSG" | grep -qE "^close-pr$"; then
          echo "Action: close PR"
          echo "action=close" >> $GITHUB_OUTPUT
        else
          echo "Action: skip (no PR action needed)"
          echo "action=skip" >> $GITHUB_OUTPUT
        fi
      shell: bash