name: 'Parse pull_request.json'
description: 'Parse pull_request.json into core PR inputs'
outputs:
  base:
    description: 'Base branch for the PR'
    value: ${{ steps.parse.outputs.base }}
  title:
    description: 'Title of the PR'
    value: ${{ steps.parse.outputs.title }}
  body:
    description: 'Body of the PR'
    value: ${{ steps.parse.outputs.body }}
  labels:
    description: 'Comma-separated list of labels'
    value: ${{ steps.parse.outputs.labels }}
  draft:
    description: 'Draft PR setting'
    value: ${{ steps.parse.outputs.draft }}
  milestone:
    description: 'Milestone number'
    value: ${{ steps.parse.outputs.milestone }}
runs:
  using: 'composite'
  steps:
    - name: Parse pull_request.json
      id: parse
      run: |
        if [ ! -f "pull_request.json" ] || ! jq -e .title "pull_request.json" >/dev/null 2>&1; then
          echo "Error: pull_request.json missing or invalid (title required)."
          exit 1
        fi
        echo "base=$(jq -r '.base // "main"' pull_request.json)" >> $GITHUB_OUTPUT
        echo "title=[AUTO] $(jq -r '.title' pull_request.json)" >> $GITHUB_OUTPUT
        echo "body=$(jq -r '.body // "Automated PR created by pull_request.json"' pull_request.json)" >> $GITHUB_OUTPUT
        echo "labels=$(jq -r '(.labels // ["auto-generated"]) | join(",")' pull_request.json)" >> $GITHUB_OUTPUT
        echo "draft=$(jq -r '.draft // false' pull_request.json)" >> $GITHUB_OUTPUT
        echo "milestone=$(jq -r '.milestone // ""' pull_request.json)" >> $GITHUB_OUTPUT
      shell: bash
