name: PR Automation from Commit Message

on:
  push:
    branches:
      - feature/*

jobs:
  check-trigger:
    runs-on: ubuntu-latest
    outputs:
      action: ${{ steps.check.outputs.action }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/check-trigger
        id: check

  pr-automation:
    needs: check-trigger
    if: needs.check-trigger.outputs.action == 'create' || needs.check-trigger.outputs.action == 'close'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse Commit Message
        id: parse
        uses: ./.github/actions/parse-commit
        if: needs.check-trigger.outputs.action == 'create'

      - name: Create Pull Request
        if: needs.check-trigger.outputs.action == 'create'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: ${{ steps.parse.outputs.base }}
          title: ${{ steps.parse.outputs.title }}
          body: ${{ steps.parse.outputs.body }}
          labels: ${{ steps.parse.outputs.labels }}

      - name: Close Open Pull Requests
        if: needs.check-trigger.outputs.action == 'close'
        run: |
          PR_EXISTS=$(gh pr list --head ${{ github.ref_name }} --state open --json number -q '.[] | .number')
          if [ -n "$PR_EXISTS" ]; then
            for PR_NUM in $PR_EXISTS; do
              echo "Closing PR #$PR_NUM"
              gh pr close $PR_NUM --comment "Closed due to close-pr commit."
            done
          else
            echo "No open PRs found for this branch."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}