name: PR Automation from Commit Message

on:
  push:
    branches:
      - feature/*

jobs:
  check-trigger:
    runs-on: ubuntu-latest
    outputs:
      action: ${{ steps.check.outputs.action }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/check-trigger
        id: check

  pr-automation:
    needs: check-trigger
    if: needs.check-trigger.outputs.action == 'create' || needs.check-trigger.outputs.action == 'close'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Automatische Test Branch
        run: |
          AUTO_TEST_BRANCH="auto-test"
          git fetch origin
          if ! git ls-remote --heads origin | grep -q "refs/heads/$AUTO_TEST_BRANCH"; then
            echo "Creating automatische test branch $AUTO_TEST_BRANCH from main"
            git checkout main
            git branch $AUTO_TEST_BRANCH
            git push origin $AUTO_TEST_BRANCH
          else
            echo "Automatische test branch $AUTO_TEST_BRANCH already exists."
          fi

      - name: Parse Commit Message
        id: parse
        uses: ./.github/actions/parse-commit
        if: needs.check-trigger.outputs.action == 'create'

      - name: Create Temporary Branch
        if: needs.check-trigger.outputs.action == 'create'
        run: |
          TEMP_BRANCH="pr-$(date +%s)-${{ github.run_id }}"
          git fetch origin ${{ steps.parse.outputs.base }}
          git checkout ${{ steps.parse.outputs.base }}
          git checkout -b "$TEMP_BRANCH"
          git push origin "$TEMP_BRANCH"
          echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        if: needs.check-trigger.outputs.action == 'create'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.TEMP_BRANCH }}
          base: "auto-test"
          title: ${{ steps.parse.outputs.title }}
          body: ${{ steps.parse.outputs.body }}
          labels: ${{ steps.parse.outputs.labels }}

      - name: Close Open Pull Requests
        if: needs.check-trigger.outputs.action == 'close'
        run: |
          PR_EXISTS=$(gh pr list --head ${{ github.ref_name }} --state open --json number -q '.[] | .number')
          if [ -n "$PR_EXISTS" ]; then
            for PR_NUM in $PR_EXISTS; do
              echo "Closing PR #$PR_NUM"
              gh pr close $PR_NUM --comment "Closed due to close-pr commit."
            done
          else
            echo "No open PRs found for this branch."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}