name: PR Automation from Commit Message

on:
  push:
    branches:
      - feature/*

jobs:
  pr-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Nodig om git log te gebruiken

      # Installeer Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Log het laatste commit-bericht voor debugging
      - name: Log Latest Commit Message
        run: |
          echo "Last commit message:"
          git log -1 --pretty=%B

      # Valideer commit en maak PR
      - name: Validate Commit and Create PR
        run: |
          poetry install --no-root
          COMMIT_DATA=$(poetry run tools/validate_commit_msg.py && echo "VALID" || echo "INVALID")
          if [ "$COMMIT_DATA" = "VALID" ]; then
            TITLE=$(git log -1 --pretty=%s)
            DESCRIPTION=$(git log -1 --pretty=%b | tail -n +2 || echo "No description provided.")
            echo "Creating PR with title: $TITLE"
            gh pr create --base main --head ${{ github.ref_name }} --title "$TITLE" --body "$DESCRIPTION" --label "auto-generated"
          else
            echo "Invalid commit message—skipping PR creation."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}