name: Manage Pull Request via Commit

on:
  push:
    branches:
      - feature/*

permissions:
  contents: write
  pull-requests: write

jobs:
  manage-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Haal laatste commit message op
        id: get-message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s)
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Haal open PRs op
        id: get-pr
        run: |
          PR_NUMBER=$(gh pr list --head ${{ github.ref_name }} --state open --json number -q '.[] | .number')
          if [ -n "$PR_NUMBER" ]; then
            echo "pr_exists=true" >> $GITHUB_OUTPUT
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          else
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Maak Pull Request aan
        if: contains(steps.get-message.outputs.message, '[PR]') && steps.get-pr.outputs.pr_exists == 'false'
        run: |
          TITLE=$(echo "${{ steps.get-message.outputs.message }}" | sed 's/\[PR\] //')
          gh pr create --base "main" --head ${{ github.ref_name }} --title "$TITLE" --body "Automatische PR door commit message"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Update Pull Request
        if: steps.get-pr.outputs.pr_exists == 'true' && !contains(steps.get-message.outputs.message, '[PR]') && !contains(steps.get-message.outputs.message, '[CLOSE PR]')
        run: |
          gh pr edit ${{ steps.get-pr.outputs.pr_number }} --title "Updated: ${{ steps.get-message.outputs.message }}" --body "Bijgewerkt door commit: ${{ steps.get-message.outputs.message }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Sluit Pull Request
        if: contains(steps.get-message.outputs.message, '[CLOSE PR]') && steps.get-pr.outputs.pr_exists == 'true'
        run: |
          gh pr close ${{ steps.get-pr.outputs.pr_number }} --comment "Gesloten door commit message [CLOSE PR]"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}