name: Manage Pull Request

on:
  push:
    branches:
      - feature/*

permissions:
  contents: write
  pull-requests: write

jobs:
  manage-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Check for pull_request.json
        id: check-file
        run: |
          if [ -f "pull_request.json" ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Get Open PRs
        id: get-pr
        run: |
          PR_NUMBER=$(gh pr list --head ${{ github.ref_name }} --state open --json number -q '.[] | .number')
          if [ -n "$PR_NUMBER" ]; then
            echo "pr_exists=true" >> $GITHUB_OUTPUT
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          else
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Parse pull_request.json
        id: parse
        uses: ./.github/actions/parse-pr-json
        if: steps.check-file.outputs.file_exists == 'true' && steps.get-pr.outputs.pr_exists == 'false'

      - name: Create Pull Request
        if: steps.check-file.outputs.file_exists == 'true' && steps.get-pr.outputs.pr_exists == 'false'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          base: ${{ steps.parse.outputs.base }}
          branch: ${{ github.ref_name }}
          title: ${{ steps.parse.outputs.title }}
          body: ${{ steps.parse.outputs.body }}
          labels: ${{ steps.parse.outputs.labels }}
          draft: ${{ steps.parse.outputs.draft }}
          milestone: ${{ steps.parse.outputs.milestone }}

      - name: Close Pull Request
        if: steps.check-file.outputs.file_exists == 'false' && steps.get-pr.outputs.pr_exists == 'true'
        run: |
          gh pr close ${{ steps.get-pr.outputs.pr_number }} --comment "Closed because pull_request.json was removed"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
