name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-poetry-
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Build Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") -t ghcr.io/brainxio/exp-42-kafkaiftastic-avalanche:$VERSION .
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker push ghcr.io/brainxio/exp-42-kafkaiftastic-avalanche:$VERSION
      - name: Generate mission artifact
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          cp artifacts/mission_template.json mission.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" mission.json
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: mission.json
          body: "Release $VERSION - See mission.json for details"
